import { useState, type ReactNode } from 'react'
import { Activity, ArrowRight, BarChart3, Bell, BrainCircuit, Check, ChevronRight, CircleAlert, ClipboardCheck, Clock3, FileText, Gauge, Home, Lightbulb, LoaderCircle, LogIn, Menu, MessageSquareText, PenLine, Plus, Send, Settings, ShieldAlert, Sparkles, Target, Users, X } from 'lucide-react'
import './App.css'

type View = 'landing' | 'login' | 'employee' | 'standup' | 'manager' | 'executive' | 'analytics'
type PageProps = { go: (view: View) => void; userName?: string; setUserName?: (name: string) => void }
const nav = [['employee', 'My workspace', Home], ['standup', 'Daily stand-up', PenLine], ['manager', 'Team pulse', Users], ['executive', 'Executive brief', FileText], ['analytics', 'Analytics', BarChart3]] as const
const people = [['Arjun Mehta', 'Product', 'AM', 'mint', 'Shipped the onboarding flow and aligned the activation event taxonomy with engineering.', 'On track'], ['Sneha Rao', 'Engineering', 'SR', 'peach', 'Waiting on the data contract before starting the cohort dashboard integration.', 'At risk'], ['Kabir Singh', 'Operations', 'KS', 'lavender', 'Completed the vendor audit and documented the new escalation process for the team.', 'On track']]

function Logo({ dark = false }: { dark?: boolean }) { return <div className={`brand ${dark ? 'brand-dark' : ''}`}><span className="brand-mark"><i /><i /><i /></span>pulse<span className="brand-dot">.</span></div> }
function Button({ children, onClick, className = '' }: { children: ReactNode; onClick?: () => void; className?: string }) { return <button className={`primary-button ${className}`} onClick={onClick}>{children}</button> }
function Landing({ go }: PageProps) { return <main className="landing-page"><nav className="landing-nav"><Logo dark /><div className="landing-links"><a href="#how">How it works</a><a href="#how">For teams</a><button onClick={() => go('login')}>Sign in <ArrowRight size={16} /></button></div><Menu className="mobile-icon" size={21} /></nav><section className="landing-hero"><div className="hero-copy"><small className="eyebrow"><Sparkles size={14} /> AI-native team rituals</small><h1>Turn daily updates into <em>clear momentum.</em></h1><p>Pulse brings every stand-up together, so teams can move from scattered updates to confident decisions.</p><Button onClick={() => go('login')}>Enter workspace <ArrowRight size={17} /></Button><div className="hero-proof"><div className="avatar-stack"><span>AM</span><span>SR</span><span>KS</span><span>+8</span></div><span>Trusted by focused teams<br /><strong>across Central Operations</strong></span></div></div><div className="hero-art"><div className="art-grid" /><div className="floating-note note-top"><Check size={16} /><div><strong>12 updates understood</strong><small>AI summary ready</small></div></div><div className="hero-window"><div className="window-head"><b>● Team pulse</b><span>Tuesday, 14 May</span></div><div className="window-score"><div><small>Team health</small><strong>84<sup>/100</sup></strong><em><Activity size={13} /> +8% this week</em></div><div className="ring">84</div></div><div className="window-chart">{[32, 48, 40, 66, 58, 82, 74, 92].map((height) => <i key={height} style={{ height: `${height}%` }} />)}</div><div className="window-foot">9 on track <span>2 need attention</span></div></div><div className="floating-note note-bottom"><ShieldAlert size={16} /><div><strong>2 risks surfaced</strong><small>Review before 10:00 AM</small></div></div></div></section><section className="landing-strip" id="how"><div><b>01</b><strong>Capture once</strong><p>One thoughtful prompt replaces scattered pings.</p></div><div><b>02</b><strong>Understand faster</strong><p>AI turns the team's voice into signal.</p></div><div><b>03</b><strong>Act with context</strong><p>Managers see what needs attention next.</p></div></section></main> }
function Login({ go, setUserName }: PageProps) {
	const [isSigningIn, setIsSigningIn] = useState(false)
	const [email, setEmail] = useState('')

	const handleSignIn = (e?: React.FormEvent) => {
		if (e) e.preventDefault()
		if (isSigningIn || !email) return
		setIsSigningIn(true)
		const name = email.split('@')[0] || 'User'
		if (setUserName) setUserName(name.charAt(0).toUpperCase() + name.slice(1))
		window.setTimeout(() => go('employee'), 1500)
	}

	return <main className="login-page"><Logo /><button className="back-button" onClick={() => go('landing')}><ArrowRight size={15} style={{ transform: 'rotate(180deg)' }} /> Back to overview</button><div className="login-panel"><small className="eyebrow">Welcome to pulse</small><h1>A calmer way to<br /><em>move work forward.</em></h1><p>Sign in to share your update or see what your team needs next.</p><form onSubmit={handleSignIn} style={{ display: 'flex', flexDirection: 'column', gap: '10px', marginTop: '20px' }}><input type="email" placeholder="Email address" required value={email} onChange={e => setEmail(e.target.value)} style={{ padding: '13px 15px', borderRadius: '5px', border: '1px solid #d1dcd5', outline: 'none', fontSize: '13px' }} /><input type="password" placeholder="Password" required style={{ padding: '13px 15px', borderRadius: '5px', border: '1px solid #d1dcd5', outline: 'none', fontSize: '13px' }} /><button type="submit" className="login-button" style={{ marginTop: '5px' }} disabled={isSigningIn}>{isSigningIn ? <><LoaderCircle className="login-spinner" size={17} /> Signing in...</> : <>Sign In <ArrowRight size={17} /></>}</button></form><small className="login-note" style={{ marginTop: '14px', display: 'block' }}>Demo Mode – Authentication is mocked for this prototype.</small></div><div className="login-art"><div className="login-orbit" /><div className="login-card"><Sparkles size={18} /><strong>Good morning, {email ? email.split('@')[0].charAt(0).toUpperCase() + email.split('@')[0].slice(1) : 'User'}</strong><small>Your team is ready for focus.</small></div></div></main>
}
function Sidebar({ view, go, userName }: { view: View; go: (v: View) => void; userName?: string }) { const initials = userName ? userName.substring(0, 2).toUpperCase() : 'U'; return <aside className="sidebar"><Logo /><div className="workspace-switcher"><span>CO</span><div><strong>Central Operations</strong><small>Operations workspace</small></div><ChevronRight size={15} /></div><span className="side-label">Workspace</span><div className="side-nav">{nav.map(([id, label, Icon]) => <button className={view === id ? 'active' : ''} onClick={() => go(id)} key={id}><Icon size={17} />{label}{id === 'manager' && <span className="nav-badge">3</span>}</button>)}</div><div className="sidebar-bottom"><button><Settings size={17} /> Settings</button><div className="user-row"><span>{initials}</span><div><strong>{userName || 'User'}</strong><small>Product manager</small></div><button onClick={() => go('landing')} aria-label="Sign out"><LogIn size={15} /></button></div></div></aside> }
function Topbar({ title, subtitle, action, userName }: { title: string; subtitle: string; action?: ReactNode; userName?: string }) { const initials = userName ? userName.substring(0, 2).toUpperCase() : 'U'; return <header className="topbar"><div><small className="breadcrumb">Central Operations <ChevronRight size={13} /> Workspace</small><h1>{title}</h1><p>{subtitle}</p></div><div className="top-actions"><button aria-label="Notifications" style={{ background: 'none', border: 'none', padding: 0, color: 'inherit' }}><Bell size={18} /></button>{action}<span className="top-avatar">{initials}</span></div></header> }
function Heading({ eyebrow, title, action, onClick }: { eyebrow: string; title: string; action?: string; onClick?: () => void }) { return <div className="section-heading"><div><small className="eyebrow">{eyebrow}</small><h2>{title}</h2></div>{action && <button className="plain-link" onClick={onClick}>{action} <ArrowRight size={15} /></button>}</div> }
function Card({ icon: Icon, tone, label, title, children }: { icon: typeof Home; tone: string; label: string; title: string; children: ReactNode }) { return <article className="insight-card"><div className="insight-head"><span className={`insight-icon ${tone}`}><Icon size={17} /></span><div><small>{label}</small><h3>{title}</h3></div><em>✦ AI</em></div>{children}</article> }
function Employee({ go, userName }: PageProps) { return <><Topbar title={`Good morning, ${userName || 'User'}`} subtitle="Tuesday, 14 May 2024 · Here's your pulse for today." action={<Button className="compact" onClick={() => go('standup')}><Plus size={16} /> Share update</Button>} userName={userName} /><div className="dashboard-content"><section className="welcome-banner"><div><small className="eyebrow">Tuesday check-in</small><h2>Your work has a rhythm.<br /><em>Keep it moving.</em></h2><p>You've shared updates <strong>4 days in a row.</strong> One more today keeps your streak alive.</p><button className="dark-button" onClick={() => go('standup')}>Share today's update <ArrowRight size={16} /></button></div><div className="streak-visual"><div className="streak-ring"><b>4</b><span>day streak</span></div><div className="streak-days"><span className="streak-done">M</span><span className="streak-done">T</span><span className="streak-done">W</span><span className="streak-today">T</span><span>F</span></div></div></section><Heading eyebrow="Your latest signal" title="What Pulse heard" action="View all updates" onClick={() => go('standup')} /><div className="insight-grid"><Card icon={BrainCircuit} tone="purple" label="AI SUMMARY" title="A clear path is forming"><p>Your work is moving from <strong>discovery to delivery.</strong></p><p>You've closed the open questions on the onboarding flow and are now creating momentum with engineering.</p><div className="confidence">Confidence <i><b /></i> 88%</div></Card><Card icon={ShieldAlert} tone="amber" label="BLOCKER DETECTED" title="One thing needs attention"><div className="blocker-row"><CircleAlert size={17} /><div><strong>Data contract dependency</strong><p>May delay cohort dashboard by 1–2 days</p></div></div><button className="card-action">Add context <ArrowRight size={14} /></button></Card><Card icon={Lightbulb} tone="blue" label="SUGGESTED NEXT ACTION" title="Protect tomorrow's focus"><p>Book a <strong>15-minute alignment</strong> with the data team before your next build session.</p><div className="suggested-time"><Clock3 size={14} /> Suggested for tomorrow <X size={14} /></div></Card></div><Heading eyebrow="Personal history" title="Recent updates" action="Open stand-up history" onClick={() => go('standup')} /><div className="updates-table"><div className="table-row table-header"><span>Date</span><span>What you shared</span><span>Pulse read</span><span /></div>{['Onboarding flow is ready for engineering handoff.', 'Mapped the top three activation drop-offs.', 'Finished discovery interviews with five users.'].map((text, i) => <div className="table-row" key={text}><span>{['Tue, 14 May', 'Mon, 13 May', 'Fri, 10 May'][i]}<small>{i ? '2024' : 'Today'}</small></span><span>{text}</span><span className={`status-pill ${i === 1 ? 'amber-pill' : 'green-pill'}`}>{i === 1 ? 'Watch' : 'On track'}</span><ChevronRight size={16} /></div>)}</div></div></> }
function Standup({ go, userName }: PageProps) { const [sent, setSent] = useState(false); if (sent) return <div className="success-state"><span><Check size={28} /></span><small className="eyebrow">Update received</small><h2>That's a wrap for today.</h2><p>Pulse is turning your update into a clear signal for you and your team.</p><Button onClick={() => go('employee')}>Back to workspace <ArrowRight size={16} /></Button></div>; return <><Topbar title="Daily stand-up" subtitle="A two-minute check-in keeps your work visible and your team aligned." action={<span className="save-note"><Check size={14} /> Saved automatically</span>} userName={userName} /><div className="form-layout"><div className="standup-form"><div className="form-progress"><i className="progress-active" /><i className="progress-active" /><i className="progress-active" /><small>3 questions</small></div><small className="eyebrow">Today's check-in</small><h2>What moved forward?</h2><p>Share the progress that matters. A few sentences are enough.</p><label>What did you accomplish since your last update?<textarea defaultValue="Shipped the onboarding flow and aligned the activation event taxonomy with engineering." /></label><label>What are you focusing on next?<textarea defaultValue="I'll pair with engineering on the first implementation and review the analytics events." /></label><label>Anything slowing you down?<textarea className="short-textarea" placeholder="No blockers? Tell us what is helping you move quickly." /></label><div className="form-footer"><span>Private to your team <ShieldAlert size={13} /></span><Button onClick={() => setSent(true)}>Submit update <Send size={16} /></Button></div></div><aside className="form-aside"><div className="aside-quote"><MessageSquareText size={20} /><p>“The best update is not the longest one. It's the one that helps someone else make a better decision.”</p><small>Pulse principle 01</small></div><div className="aside-guide"><strong>Good updates include</strong><span><Check size={14} /> A concrete outcome</span><span><Check size={14} /> What happens next</span><span><Check size={14} /> A clear ask, if you have one</span></div></aside></div></> }
function Manager({ go, userName }: PageProps) { const metrics = [{ label: 'Participation', value: '86%', Icon: Users, tone: 'mint' }, { label: 'Team health', value: '84', Icon: Gauge, tone: 'purple' }, { label: 'Need attention', value: '3', Icon: ShieldAlert, tone: 'amber' }, { label: 'Updates this week', value: '42', Icon: ClipboardCheck, tone: 'blue' }]; return <><Topbar title="Team pulse" subtitle="Central Operations · Week of 13 May 2024" action={<button className="outline-button" onClick={() => go('executive')}><FileText size={16} /> Create brief</button>} userName={userName} /><div className="dashboard-content"><div className="metric-grid">{metrics.map(({ label, value, Icon, tone }) => <div className="metric-card" key={label}><span className={`metric-icon ${tone}-icon`}><Icon size={17} /></span><div><small>{label}</small><strong>{value}</strong><em>{label === 'Need attention' ? '2 blockers · 1 risk' : '+12% this week'}</em></div></div>)}</div><div className="manager-grid"><section className="panel"><Heading eyebrow="Live today" title="Team updates" action="All teams" />{people.map(([name, role, initials, color, update, status]) => <div className="team-update" key={name}><span className={`member-avatar ${color}`}>{initials}</span><div><strong>{name}</strong><small>{role} · 8 min ago</small><p>{update}</p><span className={`status-pill ${status === 'At risk' ? 'amber-pill' : 'green-pill'}`}>{status}</span></div><ChevronRight size={17} /></div>)}</section><section className="panel"><Heading eyebrow="AI triage" title="Needs attention" action="3" />{['Data contract dependency', 'Vendor approval pending', 'Onboarding momentum'].map((title, i) => <div className="attention-item" key={title}><i className={['red-line', 'amber-line', 'blue-line'][i]} /><div><strong>{title}</strong><p>{['Sneha · Engineering', 'Kabir · Operations', 'Arjun · Product'][i]}</p><small>Decision or context needed this week</small></div><ArrowRight size={16} /></div>)}</section></div></div></> }
function Executive({ userName }: { userName?: string }) { return <><Topbar title="Executive brief" subtitle="A concise view of what leadership needs to know this week." action={<button className="outline-button"><Send size={16} /> Share brief</button>} userName={userName} /><div className="brief-page"><div className="brief-header"><div><small className="eyebrow">Week 20 · Generated 9:42 AM</small><h2>Central Operations is <em>moving well.</em></h2><p>Momentum is strong across the portfolio, with one dependency requiring a decision this week.</p></div><div className="brief-score"><b>84</b><span>team health</span></div></div><div className="brief-grid"><Card icon={BrainCircuit} tone="purple" label="EXECUTIVE SUMMARY" title="The headline"><p className="brief-copy">The team is progressing from planning into delivery. Participation is up 12% week-over-week and three major milestones moved forward. The data contract dependency is the only material risk to this week's commitments.</p></Card><Card icon={Target} tone="blue" label="NEXT BEST ACTION" title="Recommended decisions"><ol className="decision-list"><li>01　Confirm data contract owner by Wednesday.</li><li>02　Protect onboarding review time for Product + Eng.</li><li>03　Share the updated escalation playbook with leads.</li></ol></Card></div><div className="brief-bottom"><small className="eyebrow">Signals over time</small><h3>Healthy trajectory</h3><div className="mini-bars">{[45, 53, 48, 65, 72, 84].map((height) => <i key={height} style={{ height: `${height}%` }} />)}</div></div></div></> }
function Analytics({ userName }: { userName?: string }) { return <><Topbar title="Analytics" subtitle="Understand adoption, signal quality, and team momentum over time." action={<button className="filter-button"><Clock3 size={15} /> Last 30 days <ChevronRight size={14} /></button>} userName={userName} /><div className="dashboard-content"><div className="analytics-hero"><div><small className="eyebrow">Workflow health</small><h2>Small rituals. <em>Big signal.</em></h2><p>Pulse is helping teams spend less time reporting and more time moving.</p></div><strong>1,248 <small>updates understood</small></strong></div><div className="analytics-grid"><section className="panel large-chart"><Heading eyebrow="Participation" title="Consistent is the goal" action="+18.4%" /><div className="line-chart"><div className="chart-y">100%<br />75%<br />50%<br />25%<br />0%</div><div className="chart-area"><i /><b /><div>01 May　　 08 May　　 15 May　　 22 May　　 30 May</div></div></div></section><section className="panel"><Heading eyebrow="AI signal quality" title="What teams surface" />{[['74%', 'updates include useful context', ''], ['42%', 'updates have a next action', 'amber-progress'], ['18%', 'updates flag a blocker', 'blue-progress']].map(([value, text, tone]) => <div className="signal-stat" key={value}><i className={tone}><b style={{ width: value }} /></i><strong>{value}</strong> <span>{text}</span></div>)}</section></div></div></> }
function DemoBadge() { return <div style={{position: 'fixed', bottom: 12, right: 12, background: 'rgba(0,0,0,0.7)', color: 'white', padding: '6px 10px', borderRadius: 6, fontSize: 11, fontWeight: 500, zIndex: 9999, backdropFilter: 'blur(4px)', pointerEvents: 'none', border: '1px solid rgba(255,255,255,0.1)'}}>Frontend UI Prototype</div> }
function App() { const [view, setView] = useState<View>('landing'); const [userName, setUserName] = useState('User'); const go = (next: View) => setView(next); return <><DemoBadge />{view === 'landing' ? <Landing go={go} /> : view === 'login' ? <Login go={go} setUserName={setUserName} /> : <div className="app-shell"><Sidebar view={view} go={go} userName={userName} /><main className="app-main">{view === 'employee' && <Employee go={go} userName={userName} />}{view === 'standup' && <Standup go={go} userName={userName} />}{view === 'manager' && <Manager go={go} userName={userName} />}{view === 'executive' && <Executive userName={userName} />}{view === 'analytics' && <Analytics userName={userName} />}</main></div>}</> }
export default App
